package com.talon.ats.imports.domain;

public enum ImportRowStatus {
  PENDING,
  VALIDATED,
  FETCHING_RESUME,
  RESUME_QUARANTINED,
  APPLICATION_CREATED,
  SCAN_PENDING,
  EXTRACTING_TEXT,
  COMPLETED,
  INVALID,
  DUPLICATE_APPLICATION,
  SOURCE_AUTH_REQUIRED,
  RESUME_FETCH_FAILED,
  UNSAFE_FILE,
  PERSISTENCE_FAILED,
  CANCELLED
}
