package com.talon.ats.search.domain;

public enum SearchField {
  LOCATION,
  CURRENT_TITLE,
  CURRENT_COMPANY,
  SKILLS,
  APPLICATION_STAGE,
  JOB_TITLE,
  SOURCE,
  EXPERIENCE_MONTHS,
  NOTICE_PERIOD_DAYS,
  APPLIED_AT,
  AVAILABLE_FROM,
  CURRENT_COMPENSATION,
  EXPECTED_COMPENSATION
}
